---
title: "Untitled"
author: "Thomas Van Hoey"
date: "29/3/2018"
output: 
  bookdown::pdf_document2:
    fig_caption: yes
    latex_engine: xelatex
  html_document: default
header-includes:
#  - \usepackage{gb4e}
  - \usepackage{expex}
  - \usepackage{tikz}

CJKmainfont: Noto Sans CJK TC
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown


Example (\nextx) is well-known from the literature on parasitic
gaps. Here we are concerned with example formatting, not with the
interesting syntax.

\ex
I wonder which **article** *John* filed {\sl t\/} without reading {\sl e}.
\xe
It is beyond the scope of this investigation to determine exactly why
John did not read the article.

Multipart examples are equally straightforward.

\pex Two examples of parasitic gaps.
\a He is the man that John did not interview {\sl e\/} before
he gave the job to {\sl e}.
\a He is someone who John expected {\sl e\/} to be successful
though believing {\sl e\/} to be incompetent.
\xe
Here, we can speculate on why John did not do an interview before
recommending the person for a job. It is likely that the person
was a crony of John. In (\lastx b), perhaps John knew that
the ‘‘someone’’ went to prep school with the owner of the
business.



\ex
\begingl
\gla Mary$_i$ ist sicher, dass es den Hans nicht st\"oren
w\"urde seiner Freundin ihr$_i$ Herz auszusch\"utten.//
\glb Mary is sure that it the-{\sc acc} Hans not annoy would
his-{\sc dat} girlfriend-{\sc dat} her-{\sc acc} heart-{\sc acc} {out to
throw}//
\glft ‘Mary is sure that it would not annoy John to reveal her
heart to his girlfriend.’//
\endgl
\xe


\ex
\begingl
\gla 我 講 中文//
\glb 1SG speak Chinese//
\glc third line of.gloss//
\glft I speak Chinese.//
\endgl
\xe

\begin{tikzpicture}[parent anchor=south,
align=center, level distance=2em,
anchor=north, sibling distance=4em,
child anchor=north]
\node (top) {XP}
child {node {X}}
child {node {YP}
child {node {Y}}
child {node {ZP}}};
\end{tikzpicture}



A tree:
\begin{tikzpicture}[every node/.style={draw}, baseline=(top.base),
level distance=2em, sibling distance=4em, align=center,
parent anchor=south, child anchor=north, anchor=north]
\node (top) {XP}
child {node {X}}
child {node {YP}
child {node {AP}}
child {node {Y}}
child {node {ZP\\\footnotesize{}[anchor=north]}}};
\end{tikzpicture}
%
Another tree:
\begin{tikzpicture}[every node/.style={draw}, baseline=(top.base),
level distance=2em, sibling distance=4em, align=center,
parent anchor=south, child anchor=north, anchor=center] % ← look here
\node (top) {XP}
child {node {X}}
child {node {YP}
child {node {Y}}
child {node {ZP\\\footnotesize{}[anchor=center]}}};
\end{tikzpicture}
