---
title: "preprocessing multiple files from Hanchi"
author: "Thomas"
date: "20/12/2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Packages
```{r}
library(tidyverse)
library(stringr)
#library(textreadr)
```


#Preproocessing

##Read in data with sprintf
```{r}
##set ideophone
ideophone <- "熠熠"

##set list of suffixes for sprintf
suff <- c("xianqin",
          "qinhan",
          "three",
          "tang",
          "song",
          "yuan",
          "ming",
          "qing",
          "rep",
          "gigatw")


##set read in path
pathlink <- "/Users/Thomas/Desktop/data_phon/pre/%s_%s.txt"

##vector of paths to read in
invoerpad <- sprintf(pathlink, ideophone, suff)
invoerpad
```


## function definition
```{r}
clean <-possibly(function(var){
  
  text <- read_lines(var)
  
  text_relevant <- text %>%  
    str_extract_all(sprintf(".+%s.+|^\\d+\\..+", ideophone)) %>%
    unlist() %>%
    str_replace("^(\\d+\\.)", "@\\1") %>%
    paste(sep = "", collapse = "") %>%
    str_split("@") %>%
    unlist()
  
  pad <- var %>%
    str_replace_all(".txt", "_clean.txt") %>%
    str_replace_all("pre", "clean")
  
  writeLines(text_relevant, pad)
  
}, otherwise = NA_real_)
```

## execution
```{r}
map(invoerpad, clean)
```

