---
title: "tidyhanchi2"
author: "Thomas Van Hoey"
date: "10/18/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(tidytext)
library(widyr)
```

Load in dataset

```{r}
base <- read_lines("/Users/Thomas/Dropbox/Doctoraat/ideophone_scripts/segmented/test.txt") 
#base

text_df <- data_frame(base) %>% rename(text = base) %>%
  mutate(postID = row_number())
text_df
```

Sliding windows
```{r}
slide_windows <- function(tbl, doc_var, window_size) {
    # each word gets a skipgram (window_size words) starting on the first
    # e.g. skipgram 1 starts on word 1, skipgram 2 starts on word 2
    
    each_total <- tbl %>% 
        group_by(!!doc_var) %>% 
        mutate(doc_total = n(),
               each_total = pmin(doc_total, window_size, na.rm = TRUE)) %>%
        pull(each_total)
    
    rle_each <- rle(each_total)
    counts <- rle_each[["lengths"]]
    counts[rle_each$values != window_size] <- 1
    
    # each word get a skipgram window, starting on the first
    # account for documents shorter than window
    id_counts <- rep(rle_each$values, counts)
    window_id <- rep(seq_along(id_counts), id_counts)

    
    # within each skipgram, there are window_size many offsets
    indexer <- (seq_along(rle_each[["values"]]) - 1) %>%
        map2(rle_each[["values"]] - 1,
             ~ seq.int(.x, .x + .y)) %>% 
        map2(counts, ~ rep(.x, .y)) %>%
        flatten_int() +
        window_id
    
    tbl[indexer, ] %>%
        bind_cols(data_frame(window_id)) %>%
        group_by(window_id) %>%
        filter(n_distinct(!!doc_var) == 1) %>%
        ungroup
}
```

```{r}
tidy_pmi <- text_df %>%
    unnest_tokens(word, text) %>%
    add_count(word) %>%
    filter(n >= 20) %>% #maybe need to turn of for ideophones it does not make a differece for 灼灼
    select(-n) %>%
    slide_windows(quo(postID), 8) %>%
    pairwise_pmi(word, window_id)

tidy_pmi
```


```{r}
tidy_pmi2 <- text_df %>%
    unnest_tokens(word, text) %>%
    add_count(word) %>%
    #filter(n >= 20) %>% #maybe need to turn of for ideophones
    select(-n) %>%
    slide_windows(quo(postID), 8) %>%
    pairwise_pmi(word, window_id)

tidy_pmi2
```


```{r}
tidy_word_vectors <- tidy_pmi %>%
    widely_svd(item1, item2, pmi, nv = 256, maxit = 1000)
```


```{r}
tidy_word_vectors2 <- tidy_pmi %>%
    widely_svd(item1, item2, pmi, nv = 256, maxit = 1000)
```

Exploring results

```{r}
nearest_synonyms <- function(df, token) {
    df %>%
        widely(~ . %*% (.[token, ]), sort = TRUE)(item1, dimension, value) %>%
        select(-item2)
}
```

```{r}
tidy_word_vectors %>%
    nearest_synonyms("灼灼")
```
 

```{r}
tidy_word_vectors2 %>%
    nearest_synonyms("灼灼")
```


```{r}
tidy_word_vectors %>%
  nearest_synonyms("灼灼") %>%
  mutate(sj = "sj") %>%
  filter(!item1 == "灼灼") %>%
  head(15) %>%
  ggplot(aes(sj, value, label = item1)) + 
  #geom_point() +
  geom_text(family="Noto Sans CJK TC") +
  theme(text = element_text(family="Noto Sans CJK TC")) 
```

```{r}
tidy_word_vectors %>%
    filter(dimension <= 24) %>%
    group_by(dimension) %>%
    top_n(12, abs(value)) %>%
    ungroup %>%
    mutate(item1 = reorder(item1, value)) %>%
    group_by(dimension, item1) %>%
    arrange(desc(value)) %>%
    ungroup %>%
    mutate(item1 = factor(paste(item1, dimension, sep = "__"), 
                         levels = rev(paste(item1, dimension, sep = "__"))),
           dimension = factor(paste0("Dimension ", dimension),
                              levels = paste0("Dimension ", as.factor(1:24)))) %>%
    ggplot(aes(item1, value, fill = dimension)) +
    geom_col(show.legend = FALSE) +
    facet_wrap(~dimension, scales = "free_y", ncol = 4) +
    scale_x_discrete(labels = function(x) gsub("__.+$", "", x)) +
    coord_flip() +
    theme(text = element_text(family="Noto Sans CJK TC")) 
  
```





